# ~/.dotfiles/zsh/zshrc
export DOTFILES="$HOME/.dotfiles"

# Core settings
setopt AUTO_CD NO_BEEP HIST_IGNORE_ALL_DUPS SHARE_HISTORY
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history
export PATH="/opt/homebrew/bin:$PATH"

# Prompt
if [ -z "$DOTFILES_PROFILE" ]; then
  export DOTFILES_PROFILE="personal"
fi

# Load profile-specific zsh configs
PROFILE_FILE="$DOTFILES/zsh/profiles/${DOTFILES_PROFILE}.zsh"
[ -f "$PROFILE_FILE" ] && source "$PROFILE_FILE"

# Starship
STARSHIP_FILE="$DOTFILES/starship/starship_${DOTFILES_PROFILE}.toml"
export STARSHIP_CONFIG="$STARSHIP_FILE"
eval "$(starship init zsh)"

# Plugins
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Tooling
eval "$(zoxide init zsh)"
eval "$(direnv hook zsh)"

# Modular config
source $DOTFILES/zsh/aliases.zsh
source $DOTFILES/zsh/node.zsh
source $DOTFILES/zsh/fzf.zsh
source $DOTFILES/zsh/keybindings.zsh

